### PR TITLE
Rename some files to lowercase to make it work on Linux

### PR DESCRIPTION
**Pull request by Rampoina**
This is just renaming some files to all lowercase to make it work in case sensitive filesystems

### CODE REVIEW

**Comment by Rampoina** [comment]
Ah yeah, the build is failing because the sh's are not marked as executable I had to chmod them

**Comment by poVoq** [comment]
Can you please merge it in?

**Comment by Divadawm** [comment]
Being new to the github, I don't know if I could merge

**Comment by Rampoina** [comment]
Hello Divadawm you only have to press the "Merge pull request" button. This is going to automatically merge my changes with your version.

**Pull request closed without merging**
